### ISSUE TITLE
自定义校验信息  出现Unexpected template string expression  no-template-curly-in-string

### ISSUE THREAD

**Issue by Dy-Han** [react-component/field-form#162]
Unexpected template string expression  no-template-curly-in-string

如果将 单引号修改成  `  则读取不到label变量

`
const validateMessages = {

  required: '${label} is required!',
  types: {
    email: '${label} is not validate email!',
    number: '${label} is not a validate number!',
  },
  number: {
    range: '${label} must be between ${min} and ${max}',
  },

};`

**Comment by zombieJ** [comment]
用 ``` ` ``` 会使用 js 的文字模板，messages 拿到的变成了被替换后的内容。当然就拿不到啦~
