### ISSUE TITLE
这个项目生产可用么？

### ISSUE THREAD

**Issue by DiamondYuan** [react-component/field-form#22]

**Comment by zombieJ** [comment]
API 已经基本定型了，在 antd `4.0-prepare` branch [集成中](https://github.com/ant-design/ant-design/pull/17327)。集成完成后会发布正式版。

**Comment by DiamondYuan** [comment]
> API 已经基本定型了，在 antd `4.0-prepare` branch [集成中](https://github.com/ant-design/ant-design/pull/17327)。集成完成后会发布正式版。

那么单独使用这个项目呢？你们有在生产环境使用么。

**Comment by zombieJ** [comment]
可以单独使用，目前没有生产环境使用。

**Comment by DiamondYuan** [comment]
> 可以单独使用，目前没有生产环境使用。

用在生产上了，现在不算太好用。因为样式还要自己写。否则需求在外层套一个 antd 的 FormItem

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/tree/4.0-prepare
这里是带有样式的，清理一波代码后可以提前发个 alpha 版本~

**Comment by jeessy2** [comment]
@zombieJ 集成到4.0 typescript有点问题。提交了一个PR，没人理啊

**Comment by zombieJ** [comment]
@jeessy2 , ci 挂了。看了一下没问题，我合掉了。 thx~

**Comment by mushan0x0** [comment]
antd 3.x的项目可以用 https://github.com/mushan0x0/rc-form-hooks ，因为没人用我也很无奈呀，只有到处宣传一下_(:з」∠)_
