### ISSUE TITLE
a wired problem is found in form rules

### ISSUE THREAD

**Issue by CaiBirdZ** [react-component/field-form#313]
i found a problem in form rules

my code：
![image](https://user-images.githubusercontent.com/20593437/122371446-73359b80-cf92-11eb-94cb-717908b3b900.png)

If a custom component has a value in 1.21.0, it will still be checked incorrectly

But it can be executed normally in 1.20.1

**Comment by anhtran** [comment]
Yes, I confirm that cannot check required fields with below code when wrap custom component:

```js
rules={[
    { required: true, message: 'Required field' }
  ]}
```

I have to use this:

```js
rules={[
  {
    validator: (rule, value) => {
      if (!value) {
        return window.Promise.reject('Required field')
      }
      return window.Promise.resolve()
    }
  }
]}
```

**Comment by Hencky** [comment]
same problem

**Comment by a88053443** [comment]
expect fix
