### ISSUE TITLE
name keeps supporting 'a.b.c' format

### ISSUE THREAD

**Issue by kakuyogy** [react-component/field-form#32]
now I want to set value of name`['children', 1, 'level']` to 'high', so i do like this,
```js
const values = {};
lodash.set(values, ['children', 1, 'level'], 'high')
form.setFieldsValue(values);
```
but now values is {children: [undefined, {level: 'high'}]}, the children[0] is undefined, so I have no intention, but i changed children[0].

so i think you should think that name continues to support 'a.b.c' format, thank you.

**Comment by zombieJ** [comment]
Use `setFields` to set value by path instead of `lodash`.
