### ISSUE TITLE
type StoreValue should include Store[] and StoreBaseValue[]

### ISSUE THREAD

**Issue by tangye1234** [react-component/field-form#41]
![image](https://user-images.githubusercontent.com/447084/63773524-e7aad080-c90d-11e9-959c-ea0c45bac9c1.png)

when I use ant Upload Component prop fileList: `Array<UploadFile>` as the initialValues of the form, the initial `UploadFile[]` cannot be assign to StoreValue, because the only supported array is `StoreBaseValue[]`, `not Store[]`

So we need to change the typescript interface to:

```typescript
export declare type StoreValue = StoreBaseValue | Store | StoreBaseValue[] | Store[];
export interface Store {
    [name: string]: StoreValue;
}
```

**Comment by tangye1234** [comment]
Meanwhile, when there is an undefined initialValue, it means that the input is not touched and have no value set on it. Maybe it is more reasonable that we should not set an undefined initial value, but when we came to some specific component like DatePicker, what value should be used instead when the date is not touched yet?

Hope there are some examples to demonstrate your design mode

**Comment by zombieJ** [comment]
Seems store should be any type since define it is meaningless.

ref: #36
