### ISSUE TITLE
Form.List add normalize for user-defined field

### ISSUE THREAD

**Issue by ycjcl868** [react-component/field-form#42]
for example, my data structure is:

```js
{
   a: 1,
   b: 2,
   c: 3,
}
```

I want to use `Form.List` but I wouldn't transform structure in `initialValues` and submit action.

I'd like to suggest that adding `normalize` in `Form.List` transform data structure into 
user-defined field.

**Comment by zombieJ** [comment]
Maybe we can add Form.Map to handle this.

**Comment by Edu93Jer** [comment]
Hi, @ycjcl868  is this issue still open?
I am newbie to this project and would like to contribute to it.
I'd like to work on this issue if no one is.
