### ISSUE TITLE
Add form.getTouchedFieldsValue helper

### ISSUE THREAD

**Issue by mgcrea** [react-component/field-form#43]
A common use case when building large forms is to only patch updated values, eg. the user only changed one or a few fields and you want to easily produce a `PATCH` http request to apply the update on a backend. Without having to post the whole form payload every time.

Today grabbing these fields seems doable with `isFieldTouched` but would be a PITA as it would require looping over every field & I haven't found an easy way to grab all current fields namePaths (would need a `getFieldNamePaths` helper too).  

Could gladly work on a PR if needed & it is something that you would consider.

**Comment by zombieJ** [comment]
Hmmm. Not sure if we could provides `getFields` function out for user to filter themself since there are lots of `getXXXFieldsValue` if we provide this api.

**Comment by mgcrea** [comment]
Maybe with a more generic `filterFieldsValueByMeta` that would take a callback?

```js
filterFieldsValueByMeta([], meta => meta.touched)
```

Or another naming you would find more suitable.

**Comment by zombieJ** [comment]
How about `getFieldsValue(nameList?: NamePath[], filterFunc: (meta: Meta) => boolean)`?

cc @afc163 @yesmeck  @chenshuai2144

**Comment by mgcrea** [comment]
Looks clean with minimal API surface change 👍

**Comment by mgcrea** [comment]
@zombieJ any update regarding this? Could work on a PR with your latest API.

**Comment by zombieJ** [comment]
Yes, please.

**Comment by mgcrea** [comment]
@zombieJ I've updated the PR #44 with the new API, looking forward to hear your feedback.
