### ISSUE TITLE
rc-field-form 更新后,再次构建项目会报错 

### ISSUE THREAD

**Issue by Nick-Tsao** [react-component/field-form#445]
Can't resolve '@babel/runtime/helpers/esm/regeneratorRuntime in  '/server/node_modules/rc-field-form/es/utils'

**Comment by Nick-Tsao** [comment]
项目中的问题已经解决了

但是这种突然增加的依赖变更, 是否filed-form本身应该内置这个库呢?

**Comment by Gjinzhou** [comment]
具体是安装了那个依赖解决的呢？我看node_modules里面@babel/runtime/helpers/esm/regeneratorRuntime是有内容的呀

**Comment by csrigogogo** [comment]
https://github.com/babel/babel/issues/14576#issuecomment-1134846592

**Comment by Gjinzhou** [comment]
目前通过在package.json中加入
"resolutions": {
    "rc-field-form": "1.26.4"
 },
已经解决

**Comment by hellohejinyu** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/8766034/170034806-4338c7c0-ff93-425b-ad3c-71f0464b872b.png">
我也碰到了，🤷‍♂️

**Comment by hellohejinyu** [comment]
> 奇怪， `rc-field-form` 一直有依赖 `@babel/runtime`： https://github.com/react-component/field-form/blob/master/package.json#L52

依赖的 `@babel/runtime` 版本调整到最新的 `7.18.1` 呢。

**Comment by zombieJ** [comment]
https://github.com/ant-design/pro-components/issues/5273#issuecomment-1133843012

我先给 rc-field-form 发个版本，father 问题也要修一下~

**Comment by zombieJ** [comment]
+ rc-field-form@1.26.6
