### ISSUE TITLE
NamePath是否考虑支持多字段映射一个表单项得能力

### ISSUE THREAD

**Issue by weird94** [react-component/field-form#465]
类似 formily https://formilyjs.org/zh-CN/guide/advanced/destructor

目前这个能力的缺失确实导致了比较复杂的前后端数据转换

**Comment by 1075488066** [comment]
> 类似 formily https://formilyjs.org/zh-CN/guide/advanced/destructor
> 
> 目前这个能力的缺失确实导致了比较复杂的前后端数据转换

我也觉得很有需要
