### ISSUE TITLE
use `lodash/set` instead but not `lodash/fp/set`

### ISSUE THREAD

**Issue by kagawagao** [react-component/field-form#55]
`setValue` in `valueUtil` use `lodash/fp/set` to set value, this cause `setValue` will not work as expect in some case
https://github.com/react-component/field-form/blob/c65e768955f009f780a9b35a31b6f51de13a4cba/src/utils/valueUtil.ts#L22-L25

consider this situation, a variable named as `a`, and it's initial value is a `boolean`
```js
const initialValues = {
  a: true
}
```
in the form field, a field name path is `['a', 'b']`, and field update, but in `lodash/fp/set`, `a` will be transformed by [`Object(value)` ](https://github.com/lodash/lodash/blob/f9cd8f552b7c8dc4aaa6be48eb9adf026ce4cd30/fp/_baseConvert.js#L363)

```js
nested[key] = clone(index == lastIndex ? value : Object(value));
```
`a` -> `Boolean{true}`

so `setValue` will not work, `a` will always  be `true`

**Comment by zombieJ** [comment]
Why do you want to set `boolean` value to be `object` value?

**Comment by kagawagao** [comment]
use [`antd`'s `Table`](https://github.com/ant-design/ant-design/issues/4544#issuecomment-271533135) as example

there is a form to config  component props, and `loading` can be `boolean` or `object`, if we set `loading` as `true` firstly to make it work, and then we set more advanced poperties to control it.

**Comment by zombieJ** [comment]
Hmmm... in Form usage, it may not good to change field value type. `rc-field-form` removed `lodash/fp/set` to reduce bundle size. And use `rc-util` instead. Could you help to check whether it works now.

If not, welcome pr to `rc-util`.

ref: https://github.com/react-component/util/blob/master/src/utils/set.ts

**Comment by kagawagao** [comment]
fixed
