### ISSUE TITLE
关于静默校验的需求

### ISSUE THREAD

**Issue by FloaJa** [react-component/field-form#591]
需求背景: 
保单录单时需要在后台实时根据用户输入内容发起请求, 进行试算保费, 当然接口发起前是需要对部分字段进行校验的, 但是form 的校验会触发页面显示报错提示, 所以需要一种方式在用户无感知的情况下校验并在校验通过后发起请求.

现在的实现方式: 
在项目中我们使用`patch-package`对`field-Form`源码进行了修改, 使用方法大致是这样: 
```js
await form.validateFields(nameList, { noSense: true });
```
 传入noSense来判断这次校验是否是一次静默校验

遇到的问题: 
`antd-mobile`内部使用了不固定版本的`rc-field-form`, 导致`patch-package`不能稳定生效
![image](https://github.com/react-component/field-form/assets/26762352/8f6d8fc7-b384-44b9-8cd5-c3f93aeedc1f)

诉求: 
希望能通过官方的方式实现这个需求, 比如像我们现在实现方式一样增加一个参数防止页面的报错

**Comment by 1075488066** [comment]
你直接把Form.Item设置成noStyle不就行了。

**Comment by FloaJa** [comment]
> 你直接把Form.Item设置成noStyle不就行了。

如果用户手动点击下一步的时候是需要正常校验, 并且在页面显示错误信息的

**Comment by 1075488066** [comment]
> > 你直接把Form.Item设置成noStyle不就行了。
> 
> 如果用户手动点击下一步的时候是需要正常校验, 并且在页面显示错误信息的

你可以直接控制报错信息啊

**Comment by 1075488066** [comment]
> > 你直接把Form.Item设置成noStyle不就行了。
> 
> 如果用户手动点击下一步的时候是需要正常校验, 并且在页面显示错误信息的

你可以自己控制报错信息通过form.getFieldErrors

**Comment by FloaJa** [comment]
> > > 你直接把Form.Item设置成noStyle不就行了。
> > 
> > 
> > 如果用户手动点击下一步的时候是需要正常校验, 并且在页面显示错误信息的
> 
> 你可以直接控制报错信息啊
我不知道这次校验是由用户触发的, 还是后台逻辑触发的

**Comment by 1075488066** [comment]
用户操作的onValuesChange不是会有回调吗。代码执行的不会触发这个方法。

**Comment by FloaJa** [comment]
> 用户操作的onValuesChange不是会有回调吗。代码执行的不会触发这个方法。

回显或者联动场景, 通过api设置值不会触发onValuesChange

**Comment by 1075488066** [comment]
回显和联动又不是用户操作的，你自己控制一下不就行了。

**Comment by q269384828** [comment]
这个应该有了吧. `validateOnly` 参数

**Comment by FloaJa** [comment]
> 这个应该有了吧. `validateOnly` 参数

多谢了才发现, 1.31.0版本支持了, antd-mobile还没有支持到这么新的版本, 不过rcform向下兼容的, 应该可以强行使用
