### ISSUE TITLE
form.resetFields 会导致 field 子组件 unmount 两次

### ISSUE THREAD

**Issue by MinJieLiu** [react-component/field-form#62]
在 Form.Item 的 children 中 封装自定义组件

在调用 `form.resetFields` API 后

自定义组件中
```js
React.useEffect(() => {
  return () => {
    console.log(1);
  }
}, []);
```
会输出两次

**Comment by MinJieLiu** [comment]
我认为这种场景很常见，比如封装`Select` 组件，`onMount` 时加载默认数据
https://github.com/react-component/field-form/blob/master/src/Field.tsx#L477

**Comment by zombieJ** [comment]
嗯，`reset` 是通过重置组件实现的。

**Comment by zombieJ** [comment]
你的数据管理不应该在 Field 控制的组件里做 load，而是应该页面加载的时候做 load。

**Comment by MinJieLiu** [comment]
暂时用 debounce 做了处理，能接受。其实 reset 重置组件可以给一个不同的 key 值以实现一次的重置。感觉两次有点接受不了😂

**Comment by MinJieLiu** [comment]
组件化封装 Select 的接口数据都是一些很固定的，逻辑分离还是好点。使用的时候不再担心数据管理，都是为了懒。

**Comment by zombieJ** [comment]
不同 key 也是会触发 unmount + mount 的: https://codesandbox.io/s/awesome-chebyshev-obsif

**Comment by MinJieLiu** [comment]
是一次 unmount +mount ，而不是现在的两次 unmount + mount

**Comment by zombieJ** [comment]
明白了，来个 PR？~

**Comment by MinJieLiu** [comment]
#65
