### ISSUE TITLE
No way to type the form store?  

### ISSUE THREAD

**Issue by mgcrea** [react-component/field-form#70]
Did not found a documented way to type the store values. Was expecting this API (what's used by [react-hook-form](https://react-hook-form.com/get-started#TypeScript)):

```ts
type FormValues = {
  email: string;
  password: string;
};

const LoginForm: FunctionComponent<Props> = ({history}) => {
  const [form] = Form.useForm<FormValues>();
```

However `useForm` does not seem to accept a generic type.

Is there another way to type a form store or do you have another API in mind?

**Comment by zombieJ** [comment]
hi @mgcrea, do you have interested to improve this?

**Comment by Kamahl19** [comment]
This should also be able without the use of `Form.useForm`. It could look like 
```
<Form<FormValues> onFinish={}>
</Form>
```

**Comment by damiangreen** [comment]
This seems like a crucial upgrade, otherwise type safety is lost.

**Comment by Sadnyster** [comment]
This is driving me crazy since I have to remap every single form field to the type i want, although the types are the same, and I still got a bunch of another forms.

**Comment by dongliang1993** [comment]
any updates?

**Comment by suncunhu** [comment]
Have a deadline for solving this problem?
