### ISSUE TITLE
Form.onFinish does not return all initialValues

### ISSUE THREAD

**Issue by anfinil** [react-component/field-form#97]
Shouldn't `onFinish` return all `initialValues` even if they are not touched and no error? Here is example: https://codesandbox.io/s/busy-wozniak-pe2ec

Related with https://github.com/react-component/field-form/commit/9af332b689eb5ae8c9a748c970a9fc66cdaf0b75

**Comment by anfinil** [comment]
Maybe it is make sense to add some setting to Form that allow to return all `initialValues`?

**Comment by zombieJ** [comment]
You can use `getFieldsValue(true)` to get all the values.
